name: Publish

on:
  push:
    branches:
      - master
    paths:
      - ./packages/foo/**

jobs:
  publish:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
