name: Release Notes

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm --workspaces --if-present run compile
      - run: npm --workspaces --if-present run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
